---
version: "3"
services:
  app:
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      DATABASE_TYPE: postgresql
      HASH_SALT: ${HASH_SALT}
    depends_on:
      - db
    restart: always
    env_file:
      - .env
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - <application-path>/sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - <application-path>/umami-db-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
# uncomment following section if you want to use nginx-proxy-manager
# running on network named nginxproxymanager_default
# networks:
#   default:
#     name: nginxproxymanager_default
#     external: true
